#!/usr/bin/env python3
import argparse
import csv
import json
import sqlite3
from pathlib import Path

import matplotlib.pyplot as plt


DEFAULT_OUTPUT_DIR = Path("data/output/nr_v2x_highway_100veh_4lane_all_tx")
DEFAULT_STEM = "paper-100veh-4lane-all-tx-nr-v2x-west-to-east-highway"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate PRR, PIR, and CBR plots from one modified NR-V2X highway run."
    )
    parser.add_argument(
        "--db",
        type=Path,
        default=DEFAULT_OUTPUT_DIR / f"{DEFAULT_STEM}.db",
        help="SQLite DB generated by nr-v2x-west-to-east-highway_modified.",
    )
    parser.add_argument(
        "--cbr-csv",
        type=Path,
        default=None,
        help="Optional CBR CSV override. By default, CBR is read from the DB cbr table.",
    )
    parser.add_argument(
        "--plots-dir",
        type=Path,
        default=None,
        help="Directory for PNG plots. Defaults to <db parent>/plots.",
    )
    parser.add_argument("--show", action="store_true", help="Show plots interactively.")
    return parser.parse_args()


def read_metadata(db_path: Path) -> dict:
    metadata_path = db_path.with_name(f"{db_path.stem}-metadata.json")
    if not metadata_path.exists():
        return {}
    with metadata_path.open() as f:
        return json.load(f)


def resolve_cbr_csv(args: argparse.Namespace, metadata: dict) -> Path:
    if args.cbr_csv is not None:
        return args.cbr_csv
    if metadata.get("cbr_csv_path"):
        return Path(metadata["cbr_csv_path"])
    return args.db.with_name(f"{args.db.stem}-cbr-timeseries.csv")


def query_rows(db_path: Path, sql: str) -> list[sqlite3.Row]:
    if not db_path.exists():
        raise FileNotFoundError(f"Missing SQLite DB: {db_path}")
    with sqlite3.connect(db_path) as conn:
        conn.row_factory = sqlite3.Row
        return list(conn.execute(sql))


def load_prr(db_path: Path) -> list[sqlite3.Row]:
    return query_rows(
        db_path,
        """
        SELECT nodeId, Ip, range, numNieb, avrgPrr
        FROM avrgPrr
        ORDER BY nodeId
        """,
    )


def load_pir(db_path: Path) -> list[sqlite3.Row]:
    return query_rows(
        db_path,
        """
        SELECT nodeId, srcIp, dstIp, avrgPirSec, TxRxDistance
        FROM avrgPir
        ORDER BY TxRxDistance, nodeId
        """,
    )


def load_cbr_from_db(db_path: Path) -> list[dict[str, float]]:
    try:
        rows = query_rows(
            db_path,
            """
            SELECT timeSec, cbr, sensingExclusionRatio
            FROM cbr
            ORDER BY timeSec
            """,
        )
    except sqlite3.OperationalError:
        return []

    return [
        {
            "time_s": float(row["timeSec"]),
            "cbr": float(row["cbr"]),
            "sensing_exclusion_ratio": float(row["sensingExclusionRatio"]),
        }
        for row in rows
    ]


def load_cbr_from_csv(cbr_csv: Path) -> list[dict[str, float]]:
    if not cbr_csv.exists():
        raise FileNotFoundError(f"Missing CBR CSV: {cbr_csv}")
    with cbr_csv.open(newline="") as f:
        reader = csv.DictReader(f)
        return [
            {
                "time_s": float(row["time_s"]),
                "cbr": float(row["cbr"]),
                "sensing_exclusion_ratio": float(row.get("sensing_exclusion_ratio", 0.0)),
            }
            for row in reader
        ]


def load_cbr(args: argparse.Namespace, metadata: dict) -> list[dict[str, float]]:
    if args.cbr_csv is not None:
        return load_cbr_from_csv(args.cbr_csv)

    rows = load_cbr_from_db(args.db)
    if rows:
        return rows

    return load_cbr_from_csv(resolve_cbr_csv(args, metadata))


def save_or_show(path: Path, show: bool) -> None:
    plt.tight_layout()
    plt.savefig(path, dpi=220)
    print(f"Saved {path}")
    if show:
        plt.show()
    plt.close()


def plot_prr(prr_rows: list[sqlite3.Row], plots_dir: Path, show: bool) -> None:
    node_ids = [row["nodeId"] for row in prr_rows]
    prr = [row["avrgPrr"] for row in prr_rows]

    plt.figure(figsize=(9, 4.5))
    plt.scatter(node_ids, prr, s=22)
    plt.xlabel("TX node ID")
    plt.ylabel("Average PRR")
    plt.title("Packet Reception Ratio by Transmitting UE")
    plt.ylim(-0.02, 1.02)
    plt.grid(True, alpha=0.35)
    save_or_show(plots_dir / "prr_by_tx_node.png", show)

    plt.figure(figsize=(7, 4.5))
    plt.hist(prr, bins=20, range=(0.0, 1.0), edgecolor="black")
    plt.xlabel("Average PRR")
    plt.ylabel("UE count")
    plt.title("PRR Distribution")
    plt.grid(True, axis="y", alpha=0.35)
    save_or_show(plots_dir / "prr_distribution.png", show)


def plot_pir(pir_rows: list[sqlite3.Row], plots_dir: Path, show: bool) -> None:
    distance = [row["TxRxDistance"] for row in pir_rows]
    pir = [row["avrgPirSec"] for row in pir_rows]

    plt.figure(figsize=(8, 4.8))
    plt.scatter(distance, pir, s=18, alpha=0.65)
    plt.xlabel("TX-RX distance (m)")
    plt.ylabel("Average PIR (s)")
    plt.title("Packet Inter-Reception Time by Distance")
    plt.grid(True, alpha=0.35)
    save_or_show(plots_dir / "pir_by_distance.png", show)

    plt.figure(figsize=(7, 4.5))
    plt.hist(pir, bins=30, edgecolor="black")
    plt.xlabel("Average PIR (s)")
    plt.ylabel("Link count")
    plt.title("PIR Distribution")
    plt.grid(True, axis="y", alpha=0.35)
    save_or_show(plots_dir / "pir_distribution.png", show)


def plot_cbr(cbr_rows: list[dict[str, float]], plots_dir: Path, show: bool) -> None:
    time_s = [row["time_s"] for row in cbr_rows]
    cbr = [row["cbr"] for row in cbr_rows]
    sensing = [row["sensing_exclusion_ratio"] for row in cbr_rows]

    plt.figure(figsize=(9, 4.5))
    plt.plot(time_s, cbr, label="CBR", linewidth=1.8)
    if any(value > 0.0 for value in sensing):
        plt.plot(time_s, sensing, label="Sensing exclusion ratio", linewidth=1.2)
    plt.xlabel("Time (s)")
    plt.ylabel("Ratio")
    plt.title("Channel Busy Ratio")
    plt.ylim(-0.02, 1.02)
    plt.grid(True, alpha=0.35)
    plt.legend()
    save_or_show(plots_dir / "cbr_timeseries.png", show)


def plot_summary(
    prr_rows: list[sqlite3.Row],
    pir_rows: list[sqlite3.Row],
    cbr_rows: list[dict[str, float]],
    plots_dir: Path,
    show: bool,
) -> None:
    fig, axes = plt.subplots(3, 1, figsize=(9, 11))

    axes[0].hist([row["avrgPrr"] for row in prr_rows], bins=20, range=(0.0, 1.0), edgecolor="black")
    axes[0].set_xlabel("Average PRR")
    axes[0].set_ylabel("UE count")
    axes[0].set_title("PRR Distribution")
    axes[0].grid(True, axis="y", alpha=0.35)

    axes[1].scatter(
        [row["TxRxDistance"] for row in pir_rows],
        [row["avrgPirSec"] for row in pir_rows],
        s=15,
        alpha=0.55,
    )
    axes[1].set_xlabel("TX-RX distance (m)")
    axes[1].set_ylabel("Average PIR (s)")
    axes[1].set_title("PIR by Distance")
    axes[1].grid(True, alpha=0.35)

    axes[2].plot([row["time_s"] for row in cbr_rows], [row["cbr"] for row in cbr_rows], linewidth=1.8)
    axes[2].set_xlabel("Time (s)")
    axes[2].set_ylabel("CBR")
    axes[2].set_title("CBR Time Series")
    axes[2].set_ylim(-0.02, 1.02)
    axes[2].grid(True, alpha=0.35)

    fig.tight_layout()
    path = plots_dir / "prr_pir_cbr_summary.png"
    fig.savefig(path, dpi=220)
    print(f"Saved {path}")
    if show:
        plt.show()
    plt.close(fig)


def main() -> None:
    args = parse_args()
    metadata = read_metadata(args.db)
    plots_dir = args.plots_dir or args.db.parent / "plots"
    plots_dir.mkdir(parents=True, exist_ok=True)

    prr_rows = load_prr(args.db)
    pir_rows = load_pir(args.db)
    cbr_rows = load_cbr(args, metadata)

    if not prr_rows:
        raise RuntimeError("No rows found in avrgPrr. Run the simulation first.")
    if not pir_rows:
        raise RuntimeError("No rows found in avrgPir. Run the simulation first.")
    if not cbr_rows:
        raise RuntimeError("No rows found in CBR table or CSV. Run the simulation first.")

    plot_prr(prr_rows, plots_dir, args.show)
    plot_pir(pir_rows, plots_dir, args.show)
    plot_cbr(cbr_rows, plots_dir, args.show)
    plot_summary(prr_rows, pir_rows, cbr_rows, plots_dir, args.show)

    mean_prr = sum(row["avrgPrr"] for row in prr_rows) / len(prr_rows)
    mean_pir = sum(row["avrgPirSec"] for row in pir_rows) / len(pir_rows)
    mean_cbr = sum(row["cbr"] for row in cbr_rows) / len(cbr_rows)
    print(f"Mean PRR: {mean_prr:.6f}")
    print(f"Mean PIR: {mean_pir:.6f} s")
    print(f"Mean CBR: {mean_cbr:.6f}")


if __name__ == "__main__":
    main()
